# Generated by Django 3.1.1 on 2020-10-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('brand_name', models.CharField(max_length=500, null=True)),
                ('regular_price_value', models.CharField(max_length=500, null=True)),
                ('offer_price_value', models.CharField(max_length=500, null=True)),
                ('currency', models.CharField(max_length=500, null=True)),
                ('classification_l1', models.CharField(max_length=500, null=True)),
                ('classification_l2', models.CharField(max_length=500, null=True)),
                ('classification_l3', models.CharField(max_length=500, null=True)),
                ('classification_l4', models.CharField(max_length=500, null=True)),
                ('image_url', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
